botocore/data/eks/2017-11-01/service-2.json
This PR fixes shape name typo `Bool -> Boolean`
=> C2DEVEL-10817: Fix shape name typo Bool -> Boolean

botocore/data/eks/2017-11-01/service-2.json
This PR adds `EbsUser` field display in `Cluster` shape.
=> C2DEVEL-10677: EKS improvements

botocore/data/ec2/2016-11-15/service-2.json
**Closes issue(s):**
* https://jira.croc.ru/browse/C2DEVEL-11439
=> C2DEVEL-11439: add legacy support for ImportImage

botocore/data/eks/2017-11-01/service-2.json
Для большой информативности кода изменен вызов метода ModifyWorkersInstanceType
=> eks: change requestUri of ModifyWorkersInstanceType method

botocore/data/ec2/2016-11-15/service-2.json
reopen pr: https://github.com/C2Devel/botocore/pull/37
=> ec2: add VirtualizationType,HighAvailable to LaunchTemplateData

botocore/data/s3/2006-03-01/service-2.json
**Detailed description, test plan are specified in Jira issue!**
=> C2DEVEL-11751: Rebase on upstream S3 botocore API

python-botocore.spec
=> C2DEVEL-XXXX: spec: bump version, update changelog

botocore/data/autoscaling/2011-01-01/service-2.json
https://jira.croc.ru/browse/C2DEVEL-13341
=> C2DEVEL-13341: Make Notification Configurations C2-compliant

botocore/data/ec2/2016-11-15/service-2.json
Add extra dedicated host fields to api
=> C2DEVEL-12497: add extra host fields

botocore/data/cloudtrail/2013-11-01/service-2.json
https://jira.croc.ru/browse/C2DEVEL-13324
=> C2DEVEL-13324: Require S3BucketName in UpdateTrail

botocore/data/paas/2022-09-06/service-2.json
https://jira.croc.ru/browse/C2DEVEL-13266
=> C2DEVEL-13266: add method for load balancers

python-botocore.spec
=> C2DEVEL-XXXX: spec: update changelog, bump version

botocore/data/backup/2018-11-15/service-2.json
https://jira.croc.ru/browse/C2DEVEL-13591
=> C2DEVEL-13591: Бекап отдельных волюмов

botocore/data/paas/2022-09-06/service-2.json
**Closes issue:** https://jira.croc.ru/browse/C2DEVEL-14528
=> C2DEVEL-14528: Метод listBackups выводит cache

botocore/data/eks-internal/2017-11-01/examples-1.json, botocore/data/eks-internal/2017-11-01/paginators-1.json, botocore/data/eks-internal/2017-11-01/service-2.json, botocore/data/eks-internal/2017-11-01/service-2.sdk-extras.json, botocore/data/eks-internal/2017-11-01/waiters-2.json
https://jira.croc.ru/browse/C2DEVEL-14655
=> C2DEVEL-14655: add private endpoint

botocore/data/paas/2022-09-06/service-2.json
https://jira.croc.ru/browse/C2DEVEL-14727
=> C2DEVEL-14727: modify load balancers section in describe service

botocore/data/efs/2015-02-01/service-2.json
https://jira.croc.ru/browse/C2DEVEL-14855
=> C2DEVEL-14855: [EFS] Реализация сервиса v1

botocore/data/eks-internal/2017-11-01/service-2.json
Closes issue(s):
[C2DEVEL-15599](https://jira.croc.ru/browse/C2DEVEL-15599)
Detailed description, test plan and upgrade path should be specified in Jira issue!
=> C2DEVEL-15599: add TotalCPUCount and TotalMemory to CompactEKSCluster

botocore/data/admin/2024-03-01/service-2.json
https://jira.croc.ru/browse/C2DEVEL-15331
=> C2DEVEL-15331: match new IAM changes

botocore/data/paas/2022-09-06/service-2.json
**Closes issue:** https://jira.croc.ru/browse/C2DEVEL-14280
Завивит от https://github.com/C2Devel/botocore/pull/106/
=> C2DEVEL-14280: Добавить pooler в postgresql

botocore/data/backup/2018-11-15/service-2.json
=> C2DEVEL-14659: Add tag name from last recovery point to protected resource model

botocore/data/eks-internal/2017-11-01/service-2.json
**Closes issue(s):**
* [C2DEVEL-15344](https://jira.croc.ru/browse/C2DEVEL-15344)
**Detailed description, test plan and upgrade path should be specified in Jira issue!**
=> C2DEVEL-15344: Добавить deprecated признак для версий kubernetes

botocore/data/ec2/2016-11-15/service-2.json
**Closes issue(s):**
* [C2DEVEL-12379](https://jira.croc.ru/browse/C2DEVEL-12379)
**Detailed description, test plan and upgrade path should be specified in Jira issue!**
=> C2DEVEL-12379: Add ModifySecurityGroupRules API

botocore/data/ec2/2016-11-15/service-2.json
https://jira.croc.ru/browse/C2DEVEL-15441
=> C2DEVEL-15441: Add ramMonitoring as instance attribute

botocore/data/iam/2024-03-21/service-2.json
=> add IAM server certificates

botocore/data/backup/2018-11-15/service-2.json
[C2DEVEL-13939](https://jira.croc.ru/browse/C2DEVEL-13939)
=> C2DEVEL-13939: Добавить параметр "защищенности" резервными копиями экземпляров в консоли

botocore/data/ec2/2016-11-15/service-2.json
[C2DEVEL-15464](https://jira.croc.ru/browse/C2DEVEL-15464)
=> C2DEVEL-15464: Нет проверки на доступность типов вольюмов в азетках ASG

botocore/data/paas/2022-09-06/service-2.json
https://jira.croc.ru/browse/C2DEVEL-15923
=> C2DEVEL-15923: Добавить имя каждому ендпоинту PaaS сервиса

botocore/data/cloudtrail/2013-11-01/service-2.json
[C2DEVEL-15991](https://jira.croc.ru/browse/C2DEVEL-15991)
=> C2DEVEL-15991: Перевести c2-wi-ct на c2-wi-api

botocore/data/cloudwatch/2010-08-01/service-2.json
[C2DEVEL-15992](https://jira.croc.ru/browse/C2DEVEL-15992)
=> C2DEVEL-15992: add MetricName and Dimensions parameters to DescribeAlarms

botocore/data/iam/2024-03-21/service-2.json
https://jira.croc.ru/browse/C2DEVEL-15953
=>   C2DEVEL-15953: IAM API part 2

botocore/data/iam/2024-03-21/service-2.json
https://jira.croc.ru/browse/C2DEVEL-15900
=> C2DEVEL-15900 :Add Tag support for IAM Users

botocore/data/iam/2024-03-21/service-2.json
https://jira.croc.ru/browse/C2DEVEL-16789
Based on #151
=> C2DEVEL-16789: Add Tags to User shape
